### ISSUE TITLE
SuperHero Association

### ISSUE THREAD

**Issue by Thwar** [NIEM/NIEM.github.io#4]
Comparing SuperHeroBadGuyAssociation.xml and SuperHeroAssociation.xsd
I noticed BadGuy and SuperHero objects are given nc:PersonType in the extension file, but in the sample xml the BadGuy object is missing PersonNameType. 

SuperHero and BadGuy should have the same properties.

**Comment by rchawdry** [comment]
I'm assuming this is for the following repository https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero instead of the main GitHub here.

In the example XML, I'm  assuming you're looking at this blurb, where the `tns:BadGuy` element doesn't have an `nc:PersonName` element:  

```` html
   ...
    <tns:BadGuy>
		<tns:PseudonymText>Joker</tns:PseudonymText>
	</tns:BadGuy>
	<tns:SuperHero>
		<nc:PersonName>
			<nc:PersonGivenName>Bruce</nc:PersonGivenName>
			<nc:PersonSurName>Wayne</nc:PersonSurName>
		</nc:PersonName>
		<tns:PseudonymText>Batman</tns:PseudonymText>
	</tns:SuperHero>
   ...
````

Both `tns:BadGuy` and `tns:SuperHero` are declared as `nc:PersonType` types.  The relevant section where this is defined is in https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero/blob/master/association/base-xsd/niem/niem-core/3.0/niem-core.xsd and this file shows the following for the `nc:PersonType`:

```` html
  ...
  <xs:complexType name="PersonType">
    <xs:annotation>
      <xs:documentation>A data type for a human being.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="structures:ObjectType">
        <xs:sequence>
          <xs:element ref="nc:PersonName" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="nc:PersonAugmentationPoint" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  ...
````

What this means is the the `nc:PersonName` within the `nc:PersonType` has  cardinality of 0 to n.  Meaning, that `nc:PersonName` is an optional element the way that this schema is defined.  

Again, for this example, this is how it is declared.  Someone can specify a different cardinality of `minOccurs="1"` which would make this a required field.

**Comment by Thwar** [comment]
I apologize for not using the right repository, I have just started using Github. 
Thanks for the simple explanation. It was a bit confusing, without keeping in mind the little details.
