### ISSUE TITLE
MPD Specification: Update Appendices Request

### ISSUE THREAD

**Issue by pleework** [NIEM/NIEM.github.io#87]
Update all appendices in the current MPD (https://reference.niem.gov/niem/specification/model-package-description/3.0.1/model-package-description-3.0.1.html) to reflect the current version of NIEM (4.1).

**Comment by cdmgtri** [comment]
Hi - thanks for the feedback!  The NIEM Technical Architecture Committee (NTAC) is currently working on updating this specification to bring it inline with the current major release series (NIEM 4.x).

**Comment by cdmgtri** [comment]
The NTAC has a repo for the MPD specification at https://github.com/NIEM/MPD-Spec.  I've logged this issue there so that the NTAC will see it and can address it appropriately:

https://github.com/NIEM/MPD-Spec/issues/27

I'm closing the issue here in favor of the new issue in the MPD repo.  You can subscribe to notifications at the link above to follow its progress.  

Thanks!
